import type { User, Restaurant, MenuItem, Order, DeliveryPartner } from "./types"

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: "user_1",
    email: "john@example.com",
    name: "John Customer",
    phone: "+1 555-0101",
    role: "customer",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user_2",
    email: "chef@example.com",
    name: "Chef Maria",
    phone: "+1 555-0102",
    role: "kitchen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    createdAt: new Date("2023-06-20"),
  },
  {
    id: "user_3",
    email: "delivery@example.com",
    name: "Alex Delivery",
    phone: "+1 555-0103",
    role: "delivery",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "user_4",
    email: "admin@example.com",
    name: "Admin User",
    phone: "+1 555-0104",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    createdAt: new Date("2023-01-01"),
  },
]

// Dummy Restaurants
export const dummyRestaurants: Restaurant[] = [
  {
    id: "rest_1",
    name: "La Bella Italia",
    description: "Authentic Italian cuisine with fresh pasta and wood-fired pizza",
    image: "/italian-restaurant-pasta.jpg",
    rating: 4.8,
    deliveryTime: 30,
    deliveryFee: 2.99,
    cuisineType: ["Italian", "Pizza", "Pasta"],
    address: "123 Main St, Downtown",
    coordinates: { lat: 40.7128, lng: -74.006 },
    createdAt: new Date("2023-05-10"),
  },
  {
    id: "rest_2",
    name: "Dragon Bowl",
    description: "Asian fusion with ramen, sushi, and authentic stir-fry",
    image: "/asian-fusion-restaurant.jpg",
    rating: 4.6,
    deliveryTime: 25,
    deliveryFee: 2.49,
    cuisineType: ["Asian", "Ramen", "Sushi"],
    address: "456 Park Ave, Midtown",
    coordinates: { lat: 40.758, lng: -73.9855 },
    createdAt: new Date("2023-08-15"),
  },
  {
    id: "rest_3",
    name: "Burger Junction",
    description: "Premium burgers, fries, and milkshakes",
    image: "/burger-restaurant.jpg",
    rating: 4.5,
    deliveryTime: 20,
    deliveryFee: 1.99,
    cuisineType: ["Burgers", "American", "Fast Food"],
    address: "789 Oak Rd, Uptown",
    coordinates: { lat: 40.7505, lng: -73.9972 },
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "rest_4",
    name: "Spice of India",
    description: "Authentic Indian curries, tandoori, and biryani",
    image: "/indian-restaurant.jpg",
    rating: 4.7,
    deliveryTime: 35,
    deliveryFee: 3.99,
    cuisineType: ["Indian", "Curry", "Tandoori"],
    address: "321 Maple Ln, Village",
    coordinates: { lat: 40.7614, lng: -73.9776 },
    createdAt: new Date("2023-11-05"),
  },
  {
    id: "rest_5",
    name: "Taco Fiesta",
    description: "Fresh Mexican street tacos and authentic salsas",
    image: "/mexican-taco-restaurant.jpg",
    rating: 4.4,
    deliveryTime: 22,
    deliveryFee: 2.49,
    cuisineType: ["Mexican", "Tacos", "Street Food"],
    address: "654 Elm St, Arts District",
    coordinates: { lat: 40.7282, lng: -73.7949 },
    createdAt: new Date("2023-12-01"),
  },
]

// Dummy Menu Items
export const dummyMenuItems: MenuItem[] = [
  // La Bella Italia
  {
    id: "item_1",
    restaurantId: "rest_1",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, basil, and tomato sauce on crispy crust",
    image: "/margherita-pizza.png",
    price: 14.99,
    category: "Pizza",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },
  {
    id: "item_2",
    restaurantId: "rest_1",
    name: "Fettuccine Alfredo",
    description: "Creamy parmesan sauce with fresh pasta",
    image: "/fettuccine-alfredo.jpg",
    price: 16.99,
    category: "Pasta",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },
  {
    id: "item_3",
    restaurantId: "rest_1",
    name: "Lasagna Bolognese",
    description: "Layered pasta with rich meat sauce and bechamel",
    image: "/classic-lasagna.png",
    price: 15.99,
    category: "Pasta",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },

  // Dragon Bowl
  {
    id: "item_4",
    restaurantId: "rest_2",
    name: "Tonkotsu Ramen",
    description: "Rich pork bone broth with tender chashu pork",
    image: "/ramen-bowl.jpg",
    price: 13.99,
    category: "Ramen",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_5",
    restaurantId: "rest_2",
    name: "California Roll",
    description: "Crab, avocado, cucumber with sesame seeds",
    image: "/sushi-roll.jpg",
    price: 12.99,
    category: "Sushi",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_6",
    restaurantId: "rest_2",
    name: "Vegetable Tempura",
    description: "Assorted vegetables in light crispy batter",
    image: "/crispy-tempura.png",
    price: 10.99,
    category: "Appetizers",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },

  // Burger Junction
  {
    id: "item_7",
    restaurantId: "rest_3",
    name: "Classic Cheeseburger",
    description: "Beef patty, cheddar, lettuce, tomato, pickles",
    image: "/classic-cheeseburger.png",
    price: 11.99,
    category: "Burgers",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_8",
    restaurantId: "rest_3",
    name: "Double Bacon Burger",
    description: "Two patties with crispy bacon and special sauce",
    image: "/bacon-burger.jpg",
    price: 14.99,
    category: "Burgers",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_9",
    restaurantId: "rest_3",
    name: "French Fries",
    description: "Crispy golden fries with seasoning",
    image: "/crispy-french-fries.png",
    price: 4.99,
    category: "Sides",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },

  // Spice of India
  {
    id: "item_10",
    restaurantId: "rest_4",
    name: "Butter Chicken",
    description: "Tender chicken in creamy tomato sauce",
    image: "/butter-chicken-curry.jpg",
    price: 15.99,
    category: "Curry",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_11",
    restaurantId: "rest_4",
    name: "Paneer Tikka",
    description: "Marinated cottage cheese grilled with spices",
    image: "/paneer-tikka.png",
    price: 13.99,
    category: "Tandoori",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },
  {
    id: "item_12",
    restaurantId: "rest_4",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice with tender chicken",
    image: "/flavorful-biryani.png",
    price: 14.99,
    category: "Biryani",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },

  // Taco Fiesta
  {
    id: "item_13",
    restaurantId: "rest_5",
    name: "Carne Asada Tacos",
    description: "Grilled marinated beef with cilantro and onions",
    image: "/delicious-tacos.png",
    price: 10.99,
    category: "Tacos",
    available: true,
    vegetarian: false,
    createdAt: new Date(),
  },
  {
    id: "item_14",
    restaurantId: "rest_5",
    name: "Vegetarian Tacos",
    description: "Roasted vegetables with fresh guacamole",
    image: "/vegetarian-tacos.jpg",
    price: 9.99,
    category: "Tacos",
    available: true,
    vegetarian: true,
    createdAt: new Date(),
  },
]

// Dummy Orders
export const dummyOrders: Order[] = [
  {
    id: "order_1",
    customerId: "user_1",
    restaurantId: "rest_1",
    items: [
      { menuItemId: "item_1", name: "Margherita Pizza", quantity: 1, price: 14.99 },
      { menuItemId: "item_2", name: "Fettuccine Alfredo", quantity: 2, price: 16.99 },
    ],
    status: "delivered",
    subtotal: 48.97,
    deliveryFee: 2.99,
    total: 51.96,
    deliveryPartner: "user_3",
    estimatedDeliveryTime: new Date(Date.now() + 30 * 60000),
    createdAt: new Date(Date.now() - 2 * 3600000),
    updatedAt: new Date(Date.now() - 1000000),
  },
  {
    id: "order_2",
    customerId: "user_1",
    restaurantId: "rest_2",
    items: [
      { menuItemId: "item_4", name: "Tonkotsu Ramen", quantity: 1, price: 13.99 },
      { menuItemId: "item_6", name: "Vegetable Tempura", quantity: 1, price: 10.99 },
    ],
    status: "in_transit",
    subtotal: 24.98,
    deliveryFee: 2.49,
    total: 27.47,
    deliveryPartner: "user_3",
    estimatedDeliveryTime: new Date(Date.now() + 15 * 60000),
    createdAt: new Date(Date.now() - 20 * 60000),
    updatedAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: "order_3",
    customerId: "user_1",
    restaurantId: "rest_3",
    items: [
      { menuItemId: "item_7", name: "Classic Cheeseburger", quantity: 2, price: 11.99 },
      { menuItemId: "item_9", name: "French Fries", quantity: 1, price: 4.99 },
    ],
    status: "preparing",
    subtotal: 28.97,
    deliveryFee: 1.99,
    total: 30.96,
    estimatedDeliveryTime: new Date(Date.now() + 40 * 60000),
    createdAt: new Date(Date.now() - 5 * 60000),
    updatedAt: new Date(Date.now() - 2 * 60000),
  },
]

// Dummy Delivery Partners
export const dummyDeliveryPartners: DeliveryPartner[] = [
  {
    id: "delivery_1",
    userId: "user_3",
    rating: 4.9,
    completedDeliveries: 847,
    isAvailable: true,
    currentLocation: { lat: 40.7128, lng: -74.006 },
    vehicleType: "bike",
    averageDeliveryTime: 24,
  },
]
